# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  # Configuration de la box et de l'interface réseau
  config.vm.box = "geerlingguy/centos7"
  config.vm.network "private_network", ip: "10.0.0.10"

  # Configuration des ressources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  # Provisioning via Shell
  config.vm.provision "shell", inline: <<-SHELL
    # Installation de Nginx
    sudo yum install -y nginx
  SHELL

end
