# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  # Configuration commune des ressources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Configuration de la première machine virtuelle (Load Balancer)
  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/xenial64"
    lb.vm.network "private_network", ip: "10.0.0.10"
    lb.vm.hostname = "lb"
  end

  # Configuration de la deuxième machine virtuelle (Web1)
  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.network "private_network", ip: "10.0.0.11"
    web1.vm.hostname = "web1"
    web1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      echo "This is Web1" | sudo tee /var/www/html/index.html
    SHELL
  end

  # Configuration de la troisième machine virtuelle (Web2)
  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/xenial64"
    web2.vm.network "private_network", ip: "10.0.0.12"
    web2.vm.hostname = "web2"
    web2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      echo "This is Web2" | sudo tee /var/www/html/index.html
    SHELL
  end
  
end
